import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>The-Julge</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <header>헤더</header>
        <main>메인 - 깃 세팅 테스트 #3</main>
        <footer>풋터</footer>
      </div>
    </>
  );
}
