import Head from "next/head";
import Link from "next/link";
import Table from "@/components/ui/Table";

export default function Home() {
  return (
    <>
      <Head>
        <title>더 줄게 - 일자리 매칭 플랫폼</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <meta property="og:image" content="/thumbnail.jpg" />
        <meta property="og:title" content="더 줄게 - 일자리 매칭 플랫폼" />
      </Head>
      <div>
        <Table />
        <main>
          메인 페이지
          <ul className="">
            <li>
              [인증]
              <ul>
                <li>
                  <Link href="/auth/login">로그인 페이지</Link>
                </li>
                <li>
                  <Link href="/auth/signup">회원가입 페이지</Link>
                </li>
              </ul>
            </li>
            <li>
              [공통 - 공고 상세]
              <ul>
                <li>
                  <Link href="/view/1">공고 상세 페이지</Link>
                </li>
              </ul>
            </li>
            <li>
              [공통 - 검색]
              <ul>
                <li>
                  <Link href="/search/">검색 페이지</Link>
                </li>
              </ul>
            </li>
            <li>
              [사장님 - 내 가게]
              <ul>
                <li>
                  <Link href="/my-shop/">내 가게 페이지</Link>
                </li>
                <li>
                  <Link href="/my-shop/write">내 가게 - 등록 페이지</Link>
                </li>
                <li>
                  <Link href="/my-shop/edit">내 가게 - 수정 페이지</Link>
                </li>
                <li>
                  <Link href="/my-shop/jobs/1/">내 가게 - 공고 상세 페이지</Link>
                </li>
                <li>
                  <Link href="/my-shop/jobs/write/">내 가게 - 공고 등록 페이지</Link>
                </li>
                <li>
                  <Link href="/my-shop/jobs/edit/1">내 가게 - 공고 수정 페이지</Link>
                </li>
              </ul>
            </li>
            <li>
              [유저 - 내 프로필]
              <ul>
                <li>
                  <Link href="/user/">내 프로필 페이지</Link>
                </li>
                <li>
                  <Link href="/user/write">내 프로필 등록 페이지</Link>
                </li>
                <li>
                  <Link href="/user/edit">내 프로필 수정 페이지</Link>
                </li>
              </ul>
            </li>
          </ul>
        </main>
      </div>
    </>
  );
}
