import Head from "next/head";
import styles from "@/styles/index.module.css";
import DataList from "@/components/ui/DataList";
export default function SearchPage() {
  return (
    <>
      <Head>
        <title>더 줄게 - 일자리 매칭 플랫폼</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <meta property="og:image" content="/thumbnail.jpg" />
        <meta property="og:title" content="더 줄게 - 일자리 매칭 플랫폼" />
      </Head>
      <DataList />
    </>
  );
}
